
[ClassVersion("0.1.0.0"), FriendlyName("xCertReq")]
class MSFT_xCertReq : OMI_BaseResource
{
    [Key, Description("Provide the text string to use as the subject of the certificate")] String Subject;
    [Required, Description("The FQDN of the Active Directory Certificate Authority on the local area network")] String CAServerFQDN;
    [Required, Description("The name of the certificate authority, by default this will be in format domain-servername-ca")] String CARootName;
    [Write, ValueMap {'1024','2048','4096','8192'},Values {'1024','2048','4096','8192'} Description("The length of the encryption key used")] String KeyLength;
    [Write, Description("The option to allow the certificate to be exportable, by default it will be true")] Boolean Exportable;
    [Write, Description("The selection of provider for the type of encryption to be used.")] String ProviderName;
    [Write, Description("The Object Identifier that is used to name the object")] String OID;
    [Write, Description("The Keyusage is a restriction method that determines what a certificate can be used for")] String KeyUsage;
    [Write, Description("The template used for the definiton of the certificate")] String CertificateTemplate;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("The credentials that will be used to access the template in the Certificate Authority")] String Credential;
    [Write, Description("Determines if the resource will also renew a certificate within 7 days of expiration")] Boolean AutoRenew;
};
