[ClassVersion("1.0"), FriendlyName("xPfxImport")]
class MSFT_xPfxImport : OMI_BaseResource
{
[Key] string Thumbprint;
[Required] string Path;
[Key,ValueMap{"LocalMachine", "CurrentUser"},Values{"LocalMachine", "CurrentUser"}] string Location;
[Key] string Store;
[write] boolean Exportable;
[write,EmbeddedInstance("MSFT_Credential")] string Credential;
[Write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};
